# Generated by Django 5.2.16 on 2026-07-19 10:25

from django.db import migrations, models


def populate_quantity_remaining(apps, schema_editor):
    StockInTransaction = apps.get_model('stock', 'StockInTransaction')
    for tx in StockInTransaction.objects.all():
        tx.quantity_remaining = tx.quantity
        tx.save(update_fields=['quantity_remaining'])


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stocktake'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockintransaction',
            name='quantity_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockouttransaction',
            name='cogs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(populate_quantity_remaining),
    ]
