# Generated by Django 5.2.17 on 2026-08-13 03:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delay_probability',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Predicted delay probability (0-100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='risk_factors',
            field=models.JSONField(blank=True, default=dict, help_text='Feature importances and risk driver explanations'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='risk_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dynamic Supplier Risk Score (0-100)', max_digits=5),
        ),
    ]
