# Generated by Django 5.2.16 on 2026-07-19 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('core', '0002_settings_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['organization', 'created_at'], name='activity_ac_organiz_ed03fe_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['event_type'], name='activity_ac_event_t_edf288_idx'),
        ),
    ]
