import { Building, Warehouse, Zap, Shield, TrendingUp } from "lucide-react";

export const SETTING_TEMPLATES = [
  {
    id: "retail",
    name: "Standard Retail Store",
    category: "Retail & Shop",
    description: "Balanced profile ideal for physical stores with moderate inventory turnover and standard security controls.",
    iconName: "Building",
    badgeColor: "bg-blue-500/10 text-blue-400 border-blue-500/20",
    glowColor: "group-hover:border-blue-500/40",
    settings: {
      default_minimum_level: 15,
      default_reorder_level: 30,
      valuation_method: "fifo",
      enable_predictive_alerts: true,
      enable_email_notifications: true,
      enable_push_notifications: false,
      forecast_model: "moving_average",
      forecast_horizon_days: 30,
      session_timeout_minutes: 60,
      jwt_access_minutes: 60,
      jwt_refresh_days: 7,
      remember_me_days: 30,
      max_login_attempts: 5,
      lockout_duration_minutes: 15,
      password_min_length: 8,
      password_require_uppercase: true,
      password_require_lowercase: true,
      password_require_number: true,
      password_require_special: false,
    },
    highlights: ["FIFO Valuation", "Min: 15 / Reorder: 30", "Moving Average 30-Day Forecast", "Standard Security"],
  },
  {
    id: "warehouse",
    name: "High-Volume Logistics",
    category: "Distribution & Warehouse",
    description: "High safety stocks, multi-channel push & predictive alerts, and linear regression demand forecasting for large operations.",
    iconName: "Warehouse",
    badgeColor: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
    glowColor: "group-hover:border-emerald-500/40",
    settings: {
      default_minimum_level: 50,
      default_reorder_level: 150,
      valuation_method: "weighted_average",
      enable_predictive_alerts: true,
      enable_email_notifications: true,
      enable_push_notifications: true,
      forecast_model: "linear_regression",
      forecast_horizon_days: 60,
      session_timeout_minutes: 120,
      jwt_access_minutes: 120,
      jwt_refresh_days: 14,
      remember_me_days: 30,
      max_login_attempts: 5,
      lockout_duration_minutes: 30,
      password_min_length: 10,
      password_require_uppercase: true,
      password_require_lowercase: true,
      password_require_number: true,
      password_require_special: true,
    },
    highlights: ["Weighted Average Valuation", "Min: 50 / Reorder: 150", "Linear Regression 60-Day", "Push & Email Alerts"],
  },
  {
    id: "ecommerce",
    name: "Fast E-Commerce",
    category: "D2C & Online Store",
    description: "Optimized for fast-moving stock with rapid reorder triggers, exponential smoothing, and real-time push alerts.",
    iconName: "Zap",
    badgeColor: "bg-amber-500/10 text-amber-400 border-amber-500/20",
    glowColor: "group-hover:border-amber-500/40",
    settings: {
      default_minimum_level: 25,
      default_reorder_level: 75,
      valuation_method: "fifo",
      enable_predictive_alerts: true,
      enable_email_notifications: true,
      enable_push_notifications: true,
      forecast_model: "exponential_smoothing",
      forecast_horizon_days: 45,
      session_timeout_minutes: 90,
      jwt_access_minutes: 60,
      jwt_refresh_days: 7,
      remember_me_days: 14,
      max_login_attempts: 4,
      lockout_duration_minutes: 20,
      password_min_length: 10,
      password_require_uppercase: true,
      password_require_lowercase: true,
      password_require_number: true,
      password_require_special: true,
    },
    highlights: ["FIFO Valuation", "Min: 25 / Reorder: 75", "Exponential Smoothing 45-Day", "Instant Push Alerts"],
  },
  {
    id: "security_strict",
    name: "High-Security Enterprise",
    category: "Corporate & Compliance",
    description: "Strict session timeouts, complex password rules, strict brute-force lockouts, and full audit compliance.",
    iconName: "Shield",
    badgeColor: "bg-purple-500/10 text-purple-400 border-purple-500/20",
    glowColor: "group-hover:border-purple-500/40",
    settings: {
      default_minimum_level: 20,
      default_reorder_level: 40,
      valuation_method: "lifo",
      enable_predictive_alerts: true,
      enable_email_notifications: true,
      enable_push_notifications: false,
      forecast_model: "linear_regression",
      forecast_horizon_days: 30,
      session_timeout_minutes: 15,
      jwt_access_minutes: 15,
      jwt_refresh_days: 1,
      remember_me_days: 1,
      max_login_attempts: 3,
      lockout_duration_minutes: 60,
      password_min_length: 14,
      password_require_uppercase: true,
      password_require_lowercase: true,
      password_require_number: true,
      password_require_special: true,
    },
    highlights: ["LIFO Valuation", "15-Min Session Timeout", "14+ Char Complex Password", "3-Attempt Lockout"],
  },
  {
    id: "lean_jit",
    name: "Lean Just-In-Time (JIT)",
    category: "Agile Operations",
    description: "Ultra-lean safety stock buffers to minimize holding costs while leveraging high-frequency 14-day exponential forecasting.",
    iconName: "TrendingUp",
    badgeColor: "bg-cyan-500/10 text-cyan-400 border-cyan-500/20",
    glowColor: "group-hover:border-cyan-500/40",
    settings: {
      default_minimum_level: 5,
      default_reorder_level: 15,
      valuation_method: "fifo",
      enable_predictive_alerts: true,
      enable_email_notifications: true,
      enable_push_notifications: true,
      forecast_model: "exponential_smoothing",
      forecast_horizon_days: 14,
      session_timeout_minutes: 60,
      jwt_access_minutes: 60,
      jwt_refresh_days: 7,
      remember_me_days: 30,
      max_login_attempts: 5,
      lockout_duration_minutes: 15,
      password_min_length: 8,
      password_require_uppercase: true,
      password_require_lowercase: true,
      password_require_number: true,
      password_require_special: false,
    },
    highlights: ["Minimal Holding Buffer", "Min: 5 / Reorder: 15", "14-Day Fast Forecast", "Low Holding Overhead"],
  },
];

export const FIELD_LABELS = {
  default_minimum_level: "Default Minimum Level",
  default_reorder_level: "Default Reorder Level",
  valuation_method: "Valuation Method",
  enable_predictive_alerts: "Predictive Alerts",
  enable_email_notifications: "Email Notifications",
  enable_push_notifications: "Push Notifications",
  forecast_model: "Forecast Model",
  forecast_horizon_days: "Forecast Horizon (Days)",
  session_timeout_minutes: "Session Timeout (Mins)",
  jwt_access_minutes: "JWT Access Token (Mins)",
  jwt_refresh_days: "JWT Refresh Token (Days)",
  remember_me_days: "Remember Me Duration (Days)",
  max_login_attempts: "Max Login Attempts",
  lockout_duration_minutes: "Lockout Duration (Mins)",
  password_min_length: "Min Password Length",
  password_require_uppercase: "Require Uppercase",
  password_require_lowercase: "Require Lowercase",
  password_require_number: "Require Numbers",
  password_require_special: "Require Special Characters",
};
