# Generated by Django 5.2.17 on 2026-08-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandforecast',
            name='weather_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
