# Generated by Django 5.2.17 on 2026-08-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_demandforecast_weather_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandforecast',
            name='model_name',
            field=models.CharField(max_length=150),
        ),
    ]
